server.port=8082

spring.application.name=ADMIN-SERVICE

eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#username and password for admin
admin.username=admin
admin.password=Admin@admin123
management.endpoints.web.exposure.include=*

spring.datasource.url=jdbc:postgresql://localhost:5432/bus
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

resilience4j.circuitbreaker.instances.bookingService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bookingService.failureRateThreshold=10
resilience4j.circuitbreaker.instances.bookingService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.bookingService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.bookingService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.bookingService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.bookingService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.bookingService.slowCallDurationThreshold=2s


resilience4j.circuitbreaker.instances.cancelBookingService.failureRateThreshold=10
resilience4j.circuitbreaker.instances.cancelBookingService.waitDurationInOpenState=5000ms
resilience4j.circuitbreaker.instances.cancelBookingService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.cancelBookingService.slidingWindowSize=5
resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=2000ms

resilience4j.retry.instances.bookingService.maxAttempts=3
resilience4j.retry.instances.bookingService.waitDuration=2000ms
resilience4j.retry.instances.cancelBookingService.maxAttempts=3
resilience4j.retry.instances.cancelBookingService.waitDuration=2000ms

resilience4j.circuitbreaker.instances.busService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.busService.failureRateThreshold=10
resilience4j.circuitbreaker.instances.busService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.busService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.busService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.busService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.busService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.busService.slowCallDurationThreshold=2s


resilience4j.circuitbreaker.instances.routeService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.routeService.failureRateThreshold=10
resilience4j.circuitbreaker.instances.routeService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.routeService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.routeService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.routeService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.routeService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.routeService.slowCallDurationThreshold=2s

resilience4j.circuitbreaker.instances.userService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=10
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.userService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.userService.slowCallDurationThreshold=2s

resilience4j.circuitbreaker.instances.scheduleService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.scheduleService.failureRateThreshold=10
resilience4j.circuitbreaker.instances.scheduleService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.scheduleService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.scheduleService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.scheduleService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.scheduleService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.scheduleService.slowCallDurationThreshold=2s

logging.level.io.github.resilience4j.circuitbreaker=DEBUG
management.health.circuitbreakers.enabled=true
management.endpoint.circuitbreakers.enabled=true

spring.cloud.config.uri=http://localhost:8888

spring.zipkin.base-url=http://localhost:9411
spring.sleuth.sampler.probability=1.0