server.port=8888
spring.application.name=config-server

spring.active.profile=native
spring.cloud.config.server.git.uri=https://github.com/Dhivya631/Config-repo.git
spring.cloud.config.server.git.clone-on-start=true
management.endpoints.web.exposure.include=*